export const FETCH_POKEMONS_REQUEST = "FETCH_POKEMONS_REQUEST";
export const FETCH_POKEMONS_SUCCESS = "FETCH_POKEMONS_SUCCESS";
export const FETCH_POKEMONS_FAILURE = "FETCH_POKEMONS_FAILURE";

export const FETCH_RANDOM_POKEMON_REQUEST = "FETCH_RANDOM_POKEMON_REQUEST";
export const FETCH_RANDOM_POKEMON_SUCCESS = "FETCH_RANDOM_POKEMON_SUCCESS";
export const FETCH_RANDOM_POKEMON_FAILURE = "FETCH_RANDOM_POKEMON_FAILURE";
